bt_navigator:
  ros__parameters:
    use_sim_time: true
    global_frame: map
    robot_base_frame: base_footprint
    odom_topic: /robot_controller/odom
    transform_tolerance: 0.3
    default_server_timeout: 1000 # timeout that is used by each action server that is loaded by the BT Navigator in order to process the request; timeout it will use to accept the request
    bt_loop_duration: 10 # ms; frequency at which the behavior tree is executed; the frequency at which the behavior tree will generate a new tick signal
    wait_for_service_timeout: 1000 # timeout each service client will use to wait for server response
    # default_nav_to_pose_bt_xml / default_nav_through_poses_bt_xml are intentionally NOT set
    # here. They are set at launch time in simulated_robot.launch.py.